function [Column1, SDURAKKODU, lon, lat] = import_ID_DurakKodu_lon_lat(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [COLUMN1, SDURAKKODU, LON, LAT] = IMPORTFILE1(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [COLUMN1, SDURAKKODU, LON, LAT] = IMPORTFILE1(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Column1, SDURAKKODU, lon, lat] = importfile1("C:\Users\Ege\Desktop\MATLAB DERS\DURAK&ID.csv", [2, 13861]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2022 12:43:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Column1", "SDURAKKODU", "Var3", "lon", "lat", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["Column1", "SDURAKKODU", "lon", "lat"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
fprintf("ID,DURAK_KODU,Boylam(Lon),Enlem(Lat)"\n);
Column1 = tbl.Column1;
SDURAKKODU = tbl.SDURAKKODU;
lon = tbl.lon;
lat = tbl.lat;
end