function [HAT_KODU,SEFER_SURESI1] = importHatlarinSeferSuresi(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [HAT_KODU, SEFER_SURESI1] = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [HAT_KODU, SEFER_SURESI1] = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [HAT_KODU, SEFER_SURESI1] = importfile1("C:\Users\Ege\Desktop\MATLAB DERS\HatSüre.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2022 12:49:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["HAT_KODU", "Var2", "Var3", "Var4", "Var5", "SEFER_SURESI1"];
opts.SelectedVariableNames = ["HAT_KODU", "SEFER_SURESI1"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["HAT_KODU", "Var2", "Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["HAT_KODU", "Var2", "Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
HAT_KODU = tbl.HAT_KODU;
SEFER_SURESI1 = tbl.SEFER_SURESI1;
end