function [Column2, lon, lat] = importLocationsOfStops()
%IMPORTFILE Import data from a text file
%  [COLUMN2, LON, LAT] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [COLUMN2, LON, LAT] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [Column2, lon, lat] = importfile("C:\Users\Ege\Desktop\MATLAB DERS\DURAK&ID2.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2022 18:57:43

%% Input handling
filename="C:\Users\Ege\Desktop\MATLAB DERS\DURAK&ID2.csv"
% If dataLines is not specified, define defaults
    dataLines = [2, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Column2", "Var2", "Var3", "lon", "lat", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"];
opts.SelectedVariableNames = ["Column2", "lon", "lat"];
opts.VariableTypes = ["double", "string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Column2 = tbl.Column2;
lon = tbl.lon;
lat = tbl.lat;
end