function [HATKODU, YON, SIRANO1, DURAKKODU1, XKOORDINATI1, YKOORDINATI1] = importLines_StopCodes_Order_Coordinates_()
%IMPORTFILE1 Import data from a text file
%  [HATKODU, YON, SIRANO1, DURAKKODU1, XKOORDINATI1, YKOORDINATI1] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [HATKODU, YON, SIRANO1, DURAKKODU1, XKOORDINATI1, YKOORDINATI1] =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [HATKODU, YON, SIRANO1, DURAKKODU1, XKOORDINATI1, YKOORDINATI1] = importfile1("C:\Users\Ege\Desktop\MATLAB DERS\HATLAR.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2022 13:24:48

%% Input handling
filename="C:\Users\Ege\Desktop\MATLAB DERS\HATLAR.csv";
dataLines = [2, Inf];
% % If dataLines is not specified, define defaults
% if nargin < 2
%     dataLines = [2, Inf];
% end

%% Set up the Import Options and import the data
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["HATKODU", "YON", "SIRANO1", "DURAKKODU1", "XKOORDINATI1", "YKOORDINATI1", "Var7", "Var8"];
opts.SelectedVariableNames = ["HATKODU", "YON", "SIRANO1", "DURAKKODU1", "XKOORDINATI1", "YKOORDINATI1"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["HATKODU", "YON", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["HATKODU", "YON", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
HATKODU = tbl.HATKODU;
YON = tbl.YON;
SIRANO1 = tbl.SIRANO1;
DURAKKODU1 = tbl.DURAKKODU1;
XKOORDINATI1 = tbl.XKOORDINATI1;
YKOORDINATI1 = tbl.YKOORDINATI1;
end