function [Column1, SDURAKKODU] = importfileID_DURAKKODU()
%IMPORTFILE Import data from a text file
%  [COLUMN1, SDURAKKODU] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [COLUMN1, SDURAKKODU] = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Column1, SDURAKKODU] = importfile("C:\Users\Ege\Desktop\MATLAB DERS\DURAK&ID.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Jan-2022 20:02:18

%% Input handling

% If dataLines is not specified, define defaults
filename="C:\Users\Ege\Desktop\MATLAB DERS\DURAK&ID2.csv";
dataLines= [2, Inf];
%

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Column1", "SDURAKKODU", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["Column1", "SDURAKKODU"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Column1 = tbl.Column1;
SDURAKKODU = tbl.SDURAKKODU;
end